<ul id="dialog">
    <li><a href="javascript://" onClick="$('#dialog').remove();pettie.pet.touch()">Touch</a></li>
    <li><a href="javascript://" onClick="$('#dialog').remove();pettie.pet.hit()">Hit</a></li>
    <li><a href="javascript://" onClick="$('#dialog').remove();pettie.pet.cute()">Cute</a></li>
	<li><a href="javascript://" onClick="$('#dialog').remove();pettie.pet.trick()">Trick</a></li>
</ul>
