<div id="GameList">
    <a onclick="$('#dialog').remove();guessnumber();" onmouseover="gameinfoguessnumber()" id="GameList_guess">
		<img src="<?php echo PETTIE_URL;?>images/guessBtn.png" alt="catchBtn" id="guessimg" onmouseover="mouseOverguess()" onmouseout="mouseOutguess()"/>
	</a>
    <a onclick="$('#dialog').remove();guessPic();"  onmouseover="gameinfocatchbutterfly()" id="GameList_catch">
		<img src="<?php echo PETTIE_URL;?>images/catchBtn.png" alt="catchBtn" id="catchimg" onmouseover="mouseOvercatch()" onmouseout="mouseOutcatch()"/>
	</a>
<div id="gameinfo">Information~</div>
</div>
