<script language="javascript">

function check_data(){
  if(document.getElementById("password").value.length==0){
    alert("Please enter password");
    return false;
  }
  
  if(document.getElementById("password").value.length>10){
    alert("New Passwor must be less then 10 word");
    return false;
  }
  
  if(document.getElementById("re_password").value.length>10){
    alert("Re-enter password must be less than 10 word");
    return false;
  }
  
  if(document.getElementById("password").value!=document.getElementById("re_password").value){
    alert("New Passwor and Re-enter password must be same");
    return false;
  }
} 
</script>

<form method="POST" action="<?php echo PETTIE_URL ?>member/editPassword/" onSubmit="return check_data()">
<table>
  <tr><th>Old Password :</th><td><input type="password" name="old_password" id="old_password" ></td><td></td></tr>
  <tr><th>New Password :</th><td><input name="password" type="password" id="password"/></td><td></td></tr>
  <tr><th>Re-enter password :</th><td><input name="password" type="password" id="re_password"/></td><td></td></tr>
</table>
 <input type="submit" />
</form>
