(function(){var t={}.hasOwnProperty,h=function(a,c){function s(){this.constructor=a}for(var e in c)t.call(c,e)&&(a[e]=c[e]);s.prototype=c.prototype;a.prototype=new s;a.__super__=c.prototype;return a},d=window,b=function(a){var c;this.canvas=a;c=this;this.context=this.canvas.getContext("2d");this.drawables=[];this.canOpWork=!0;this.canvas.addEventListener("click",function(a){var e;a.cancelBubble=!0;a.stopPropagation();e=c.getMouse(a);c.canOpWork&&c.drawables.forEach(function(c){if("function"===typeof c.click&&
c.contains(e))return c.click(a,e)})});this.canvas.addEventListener("mousedown",function(a){var e,b,d,g,f;a.cancelBubble=!0;a.stopPropagation();b=c.getMouse(a);f=c.drawables;d=0;for(g=f.length;d<g;d++)e=f[d],"function"===typeof e.mousedown&&e.contains(b)&&e.mousedown(a,b)});this.canvas.addEventListener("mouseup",function(a){var e,b,d,f,g;a.cancelBubble=!0;a.stopPropagation();b=c.getMouse(a);g=c.drawables;d=0;for(f=g.length;d<f;d++)e=g[d],"function"===typeof e.mouseup&&e.contains(b)&&e.mouseup(a,b)});
this.canvas.addEventListener("mousemove",function(a){var e,b,d,g,f;a.cancelBubble=!0;a.stopPropagation();b=c.getMouse(a);f=c.drawables;d=0;for(g=f.length;d<g;d++)e=f[d],"function"===typeof e.mousemove&&e.contains(b)&&e.mousemove(a,b)})};b.prototype.addDrawable=function(a){a.setContext(this.context);this.drawables.push(a)};b.prototype.getMouse=function(a){var c,b,e;c=this.canvas;b=e=0;if(void 0!==c.offsetParent){b+=c.offsetLeft;for(e+=c.offsetTop;c=c.offsetParent;)b+=c.offsetLeft,e+=c.offsetTop}return{x:a.pageX-
b,y:a.pageY-e}};d.CanvasState=b;d=window;b=function(a,c,b,e){this.x=a;this.y=c;this.width=null!=b?b:0;this.height=null!=e?e:0;this.setFillStyle();this.setStrokeStyle();this.setFont();this.setTextBaseline();this.setLineWidth();this.setFill();this.setOffsetX();this.setOffsetY();this.setRotation()};b.prototype.setX=function(a){this.x=null!=a?a:0};b.prototype.getX=function(){return this.x};b.prototype.setY=function(a){this.y=null!=a?a:0};b.prototype.getY=function(){return this.y};b.prototype.setOffsetX=
function(a){this.offsetX=null!=a?a:0};b.prototype.getOffsetX=function(){return this.offsetX};b.prototype.setOffsetY=function(a){this.offsetY=null!=a?a:0};b.prototype.getOffsetY=function(){return this.offsetY};b.prototype.setWidth=function(a){this.width=null!=a?a:0};b.prototype.getWidth=function(){return this.width};b.prototype.setHeight=function(a){this.height=null!=a?a:0};b.prototype.getHeight=function(){return this.height};b.prototype.setFillStyle=function(a){this.fillStyle=null!=a?a:"black"};b.prototype.getFillStyle=
function(){return this.fillStyle};b.prototype.setStrokeStyle=function(a){this.strokeStyle=null!=a?a:"black"};b.prototype.getStrokeStyle=function(){return this.strokeStyle};b.prototype.setFont=function(a){this.font=null!=a?a:"16px sans-serif"};b.prototype.getFont=function(){return this.font};b.prototype.setTextBaseline=function(a){this.textBaseline=null!=a?a:"top"};b.prototype.getTextBaseline=function(){return this.textBaseline};b.prototype.setContext=function(a){this.context=a};b.prototype.getContext=
function(){return this.context};b.prototype.setLineWidth=function(a){this.lineWidth=null!=a?a:1};b.prototype.getLineWidth=function(){return this.lineWidth};b.prototype.setFill=function(a){this.fill=null!=a?a:1};b.prototype.getFill=function(){return this.fill};b.prototype.setRotation=function(a){this.rotation=null!=a?a:0};b.prototype.getRotation=function(){return this.rotation};b.prototype.configContext=function(){this.context.save();this.context.fillStyle=this.fillStyle;this.context.strokeStyle=this.strokeStyle;
this.context.font=this.font;this.context.textBaseline=this.textBaseline;this.context.lineWidth=this.lineWidth;this.context.rotate(this.rotation)};b.prototype.restoreContext=function(){this.context.restore()};b.prototype.draw=function(){this.configContext();this.onDraw();this.restoreContext()};b.prototype.onDraw=function(){throw Error("please implement onDraw method for",this);};b.prototype.contains=function(){throw Error("please implement contains method for",this);};d.Drawable=b;var d=window,q=function(a,
c,b,e){q.__super__.constructor.call(this,a,c,b,e)};h(q,Drawable);q.prototype.onDraw=function(){this.getFill()?this.context.fillRect(this.x+this.getOffsetX(),this.y+this.getOffsetY(),this.width,this.height):this.context.strokeRect(this.x+this.getOffsetX(),this.y+this.getOffsetY(),this.width,this.height)};q.prototype.contains=function(a){var c,b,e,d;c=this.getX();e=this.getX()+this.getWidth();b=this.getY();d=this.getY()+this.getHeight();return a.x<=e&&a.x>=c&&a.y<=d&&a.y>=b?!0:!1};d.RectDrawable=q;
var d=window,k=function(a,c,b,e,d){k.__super__.constructor.call(this,c,b,e,d);this.setText(a)};h(k,Drawable);k.prototype.setText=function(a){this.text=a};k.prototype.getText=function(){return this.text};k.prototype.onDraw=function(){this.setHeight(parseInt(this.font,10));this.getFill()?this.context.fillText(this.getText(),this.getX()+this.getOffsetX(),this.getY()+this.getOffsetY()):this.context.strokeText(this.getText(),this.getX()+this.getOffsetX(),this.getY()+this.getOffsetY())};k.prototype.contains=
function(a){var c,b,e,d;c=this.getX();e=this.getX()+this.getWidth();b=this.getY();d=this.getY()+this.getHeight();return a.x<=e&&a.x>=c&&a.y>=b&&a.y<=d?!0:!1};k.prototype.getWidth=function(){var a;this.configContext();a=this.context.measureText(this.text).width;this.setWidth(a);this.restoreContext();return this.width};d.TextDrawable=k;var d=window,r=function(a,c,b,e,d){this.image=a;r.__super__.constructor.call(this,c,b,e,d)};h(r,RectDrawable);r.prototype.onDraw=function(){if(this.getWidth()&&this.getHeight())return this.context.drawImage(this.image,
this.x+this.getOffsetX(),this.y+this.getOffsetY(),this.width,this.height);this.context.drawImage(this.image,this.x,this.y);this.setWidth(this.image.width);return this.setHeight(this.image.height)};r.prototype.setImg=function(a){this.image=a;console.assert(void 0!==this.image.src)};d.ImageDrawable=r;var d=window,g=function(a,c,b,e,d){this.radius=a;this.startAngel=null!=c?c:0;this.endAngel=null!=b?b:360;g.__super__.constructor.call(this,e,d)};h(g,Drawable);g.prototype.setRadius=function(a){this.radius=
a};g.prototype.getRadius=function(){return this.radius};g.prototype.setStartAngel=function(a){this.startAngel=a};g.prototype.getStartAngel=function(){return this.startAngel};g.prototype.setEndAngel=function(a){this.endAngel=a};g.prototype.getEndAngel=function(){return this.endAngel};g.prototype.onDraw=function(){this.context.beginPath();this.context.arc(this.getX()+this.getOffsetX(),this.getY()+this.getOffsetY(),this.getRadius(),this.getStartAngel(),this.getEndAngel(),!0);this.getFill()?this.context.fill():
this.context.stroke()};g.prototype.contains=function(){return pMousePos.x<this.getX()+this.getRadius()&&pMousePos.x>this.getX()-this.getRadius()&&pMousePos.x<this.getX()+this.getRadius()&&pMousePos.x>this.getX()-this.getRadius()?!0:!1};d.ArcDrawable=g;var d=window,n=function(a){n.__super__.constructor.call(this,a.x,a.y,a.width,a.height);this.subView=[]};h(n,Drawable);n.prototype.add=function(a){a.setContext(this.context);this.subView.push(a)};n.prototype.setContext=function(a){n.__super__.setContext.call(this,
a);this.subView.forEach(function(c){c.setContext(a)})};d.View=n;var d=window,f=function(a){this.value=a.value;this.maxValue=a.maxValue;this.fillBlock=new RectDrawable(a.x,a.y,this.getDrawingRectWidth(a.value,a.maxValue)/a.maxValue*a.width,a.height);this.fillBlock.setFill(1);this.fillBlock.setLineWidth(0);this.strokeBlock=new RectDrawable(a.x,a.y,a.width,a.height);this.strokeBlock.setFill(0);f.__super__.constructor.call(this,a);this.add(this.fillBlock);this.add(this.strokeBlock)};h(f,View);f.prototype.setValue=
function(a){this.value=a;0>this.value&&(this.value=0);this.fillBlock.setWidth(this.getDrawingRectWidth(this.value,this.maxValue)/this.maxValue*this.width)};f.prototype.onDraw=function(){this.fillBlock.draw();this.strokeBlock.draw()};f.prototype.contains=RectDrawable.prototype.contains;f.prototype.setOffsetX=function(a){this.offsetX=a;this.fillBlock.setOffsetX(this.offsetX);this.strokeBlock.setOffsetX(this.offsetX)};f.prototype.setOffsetY=function(a){this.offsetY=a;this.fillBlock.setOffsetY(this.offsetY);
this.strokeBlock.setOffsetY(this.offsetY)};f.prototype.setFillStyle=function(a){this.fillStyle=a;this.fillBlock.setFillStyle(this.fillStyle)};f.prototype.setStrokeStyle=function(a){this.strokeStyle=a;this.strokeBlock.setStrokeStyle(this.strokeStyle)};f.prototype.getDrawingRectWidth=function(a,c){for(;a>c;)a-=c;return a};d.PrograssBar=f;var d=window,j=function(a){this.value=a.value;this.maxValue=a.maxValue;this.caption=a.caption;this.captionText=new TextDrawable(this.caption,a.x,a.y);this.prograssbar=
new PrograssBar({x:a.x,y:a.y,width:100,height:16,value:this.value,maxValue:this.maxValue});this.valueText=new TextDrawable(""+this.value+"/"+this.maxValue,a.x,a.y);j.__super__.constructor.call(this,a);this.add(this.captionText);this.add(this.prograssbar);this.add(this.valueText)};h(j,View);j.prototype.onDraw=function(){var a;this.prograssbar.setOffsetX(this.captionText.getWidth()+5);this.valueText.setOffsetX(this.captionText.getWidth()+this.prograssbar.getWidth()+5);this.captionText.draw();0.75<=
this.value/this.maxValue?this.setFillStyle("green"):0.25<=(a=this.value/this.maxValue)&&0.75>a?this.setFillStyle("orange"):0.25>this.value/this.maxValue&&this.setFillStyle("red");this.prograssbar.draw();this.valueText.draw()};j.prototype.setText=function(a){this.text=a;this.captionText.setText(this.text)};j.prototype.setValue=function(a){this.value=a;this.value=parseInt(this.value);this.prograssbar.setValue(this.value);this.valueText.setText(""+this.value+"/"+this.maxValue)};j.prototype.setFillStyle=
function(a){this.prograssbar.setFillStyle(a)};j.prototype.setStrokeStyle=function(a){this.prograssbar.setStrokeStyle(a)};j.prototype.setFont=function(a){this.font=a;this.captionText.setFont(this.font);return this.valueText.setFont(this.font)};j.prototype.contains=function(a){return a.x>this.captionText.x&&a.x<this.valueText.x+this.valueText.width&&a.y>this.y&&a<this.prograssbar.y+this.prograssbar.height?!0:!1};d.AttributeBar=j;var d=window,p=function(a){p.__super__.constructor.call(this,0,0,a.width,
a.height);this.imgSource=a.img;this.movingPx=a.movingPixel;this.actiontypes=a.actiontypes;this.actionstates=a.actionstates;this.currentAction=this.actiontypes.staying;this.currentState=this.actionstates.staying0};h(p,Drawable);p.prototype.contains=function(a){var c,b;return this.x<(c=a.x)&&c<this.x+this.width&&this.y<(b=a.y)&&b<this.y+this.width};p.prototype.onDraw=function(){this.consumeState();this.x+=this.currentState.offsetX*this.movingPx;this.y+=this.currentState.offsetY*this.movingPx;return this.context.drawImage(this.imgSource,
this.currentState.image_col_index*this.width,this.currentState.image_row_index*this.height,this.width,this.height,this.x,this.y,this.width,this.height)};p.prototype.consumeState=function(){null!==this.currentAction&&void 0!==this.currentAction&&(this.currentState=ActionStates[this.currentState[this.currentAction]])};d.Spirit=p;var d=window,l=function(a){l.__super__.constructor.call(this,a.x,a.y,a.width,a.height);this.baseImg=a.baseImg;this.maskImg=a.maskImg;this.percentage=0;this.baseCanvas=document.createElement("canvas");
this.baseContext=this.baseCanvas.getContext("2d");this.bufferCanvas=document.createElement("canvas");this.bufferContext=this.bufferCanvas.getContext("2d");this.baseCanvas.width=this.width;this.baseCanvas.height=this.height;this.bufferCanvas.width=this.width;this.bufferCanvas.height=2*this.height;this.bufferContext.drawImage(this.maskImg,0,0,this.width,this.height);this.baseContext.drawImage(this.baseImg,0,0,this.width,this.height)};h(l,Drawable);l.prototype.setPercentage=function(a){this.percentage=
a};l.prototype.onDraw=function(){var a,c,b,e,d,f;this.bufferContext.clearRect(0,this.height,this.width,this.height);this.bufferContext.fillRect(0,this.height+(15+(this.height-10-15)*(1-this.percentage)),this.width,(this.height-10-15)*this.percentage+10);c=this.bufferContext.getImageData(0,this.height,this.width,this.height);b=a=0;for(e=c.data.length-3;a<=e;b=a+=4)255===c.data[0]&&(255===c.data[1]&&255===c.data[2])&&(c.data[b+3]=0);e=this.bufferContext.getImageData(0,0,this.width,this.height);a=this.baseContext.getImageData(0,
0,this.width,this.height);b=d=3;for(f=c.data.length;d<=f;b=d+=4)c.data[b]=this.getTransparentForBorder(this.getTransparentForMask(c.data[b],e.data[b]),a.data[b]);this.bufferContext.putImageData(c,0,this.height);this.context.drawImage(this.bufferCanvas,0,this.height,this.width,this.height,this.x,this.y,this.width,this.height)};l.prototype.getTransparentForMask=function(a,b){return 200<a&&200<b?255:0};l.prototype.getTransparentForBorder=function(a,b){return 200<a||200<b?255:0};l.prototype.contains=
RectDrawable.prototype.contains;d.ExpBar=l;var d=window,m=function(a){m.__super__.constructor.call(this,a.x,a.y,a.width,a.height);this.subView=[]};h(m,Drawable);m.prototype.add=function(a){a.setContext(this.context);this.subView.push(a)};m.prototype.setContext=function(a){m.__super__.setContext.call(this,a);this.subView.forEach(function(b){b.setContext(a)})};m.prototype.onDraw=function(){var a,b,d,e;e=this.subView;b=0;for(d=e.length;b<d;b++)a=e[b],0===b?a.setX(this.x):a.setX(this.subView[b-1].x+this.subView[b-
1].width),a.setY(this.y),a.draw()};m.prototype.contains=function(a){var b,d,e,f,g;b=!1;g=this.subView;e=0;for(f=g.length;e<f;e++)d=g[e],d.contains(a)&&(b=!0);return b};d.LinearLayout=m}).call(this);
